adult.data=read.csv("c:/Users/arunesh/Downloads/adult.csv",header = T,na.strings = c(""))
View(adult.data)
names(adult.data)
anyNA(adult.data)
sapply(adult.data, function(x) length(unique(x)))
length(adult.data[adult.data$NATIVECOUNTRY == "?",])
table(adult.data$NATIVECOUNTRY)
table(adult.data$ABOVE50K)
adult.data$NATIVECOUNTRY=ifelse(adult.data$NATIVECOUNTRY=="?",NA,adult.data$NATIVECOUNTRY)
adult.data$NATIVECOUNTRY
sapply(adult.data,function(x) sum(is.na(x)))
sapply(adult.data,function(x) length(unique(x)))
library(DataExplorer)
plot_str(adult.data)
PlotMissing(adult.data)
plot_histogram(adult.data)
plot_correlation(adult.data,type = "continuous","ABOVE50K")
plot_bar(adult.data)
create_report(adult.data)
